docker_build('shared-gateway-tilt', '../../factory-shared-microgateway')

k8s_yaml(helm('../../microgateway-base-helm', name='shared-gateway-deployment', values='./values.yaml'))

k8s_resource('shared-gateway-deployment-kl-microgateway', labels=['shared-gateway'], port_forwards=8080)
