apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: pact-postgres
  name: pact-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pact-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: pact-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: pact-postgres
        - name: POSTGRES_USER
          value: pact-postgres
        image: postgres
        name: pact-postgres
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/pact-postgresql/data
          name: pact-postgres-claim0
      restartPolicy: Always
      volumes:
      - name: pact-postgres-claim0
        persistentVolumeClaim:
          claimName: pact-postgres-claim0

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: pact-postgres-claim0
  name: pact-postgres-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: pact-postgres
  name: pact-postgres
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 4455
    targetPort: 0
  selector:
    service: pact-postgres